/*  Imp...
CSR ->	In react everything is CSR client side rendering  | You can make next’s CSR by adding “use client” in top and use use effect , onClick functionality  , useState other things .

SSR ->  SSR server side rendering , it usually used in Next.js when you’re not using any onClick or useState or useEffect etc things | not doing client side rendering 

SSG -> 	static site generation is a method of building websites where HTML pages are generated at build time, rather than on each user request. This means that your web app’s content is pre-rendered into static files (like .html, .css, and .js) when the site is built and then served instantly when a user visits. | Static = fixed and already built , Site = your web pages, Generation = creation of those pages during the build process.  

Hydration in nextjs -> Hydration is the process where React takes the static HTML (generated by Next.js using SSG or SSR) and attaches the React runtime to it in the browser — making it fully interactive */









export default async function Blog({params } :{

    params : Promise <{
        blogId : string
    }>
} ){

    const blogId = (await params).blogId;


    return <div>

        {blogId}

    </div>
}